#!/usr/bin/env python3
from getch import getch
import skilstak.colors as c


red0 = c.base2 + '''
-----^------
   /  \\
  (    )
  (    )
  (    )
   \  /
    ``
'''

yellow0 = c.base2 + '''
-----^------
   /  \\
  (    )
  (    )
  (    )
   \  /
    ``
'''

green0 = c.base2 + '''
-----^------
   /  \\
  (    )
  (    )
  (    )
   \  /
    ``
'''

blue0 = c.base2 + '''
-----^------
   /  \\
  (    )
  (    )
  (    )
   \  /
    ``
'''

red1 = c.red + '''
-----^------
   /  \\
  (    )
  (    )
  (    )
   \  /
    ``
'''

yellow1 = c.yellow + '''
-----^------
   /  \\
  (    )
  (    )
  (    )
   \  /
    ``
'''

green1 = c.green + '''
-----^------
   /  \\
  (    )
  (    )
  (    )
   \  /
    ``
'''

blue1 = c.cyan + '''
-----^------
   /  \\
  (    )
  (    )
  (    )
   \  /
    ``
'''

redstat = red0
yellowstat = yellow0
greenstat = green0
bluestat = blue0
# On or off of "light". 0 is off, 1 is on

def printall():
	print(c.clear + redstat + yellowstat + greenstat + bluestat)

printall()
while True:
    key = getch()
    if key == "1":
        if redstat == red0:
            redstat = red1
            printall()
        elif redstat == red1:
            redstat = red0
            printall()
    elif key == "2":
        if yellowstat == yellow0:
            yellowstat = yellow1
            printall()
        elif yellowstat == yellow1:
            yellowstat = yellow0
            printall()
    elif key == "3":
        if greenstat == green0:
            greenstat = green1
            printall()
        elif greenstat == green1:
            greenstat = green0
            printall()
    elif key == "4":
        if bluestat == blue0:
            bluestat = blue1
            printall()
        elif bluestat == blue1:
            bluestat = blue0
            printall()
    elif key == '\x03':
        raise KeyboardInterrupt()
    else:
        print(c.red + 'Not a choice')
