#!/bin/sh

# A script to connect to the onboard Pi, which has a line in it's bashrc to run the main program once logged in.
# Make sure SSH keys are set up, so you don't need a password.
# Must run on boot, so I can do things faster.

ip="#Place IP Here!"
port="22"
# The internal ip for the onboard Pi

ssh pi@$ip -p $port	# Needs SSH keys!